### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by geniuskey** [CRA7C/TradingSystem#1]
- [x] StockerBrocker Driver Interface 개발 @gk1whd2 하종희님
- [x] Auto Trading System 모듈 개발 @currycurry3030 박병준님
- [x] 키워 Driver 개발 @jwh1308 정우훈님
- [x] 네모 Driver 개발 @winsowss 여인표님
- [x] Mock Driver 개발 @gk1whd2 하종희님
- [x] 각 TC 개발 @geniuskey 김의윤
- [x] 기능 1 : buy_nice_timing(종목, 금액) @jwh1308 정우훈님
- [x] 기능 2 : sell_nice_timing(종목, 수량) @winsowss 여인표님

**Comment by geniuskey** [comment]
모두 고생하셨습니다 :)
